<?php

namespace site\controllers;

use app\models\Product;

class CartController extends \app\base\Controller {
    public $cart;

    public function actionIndex(){
        $products =Product::find()->where(['id' =>array_keys($this->cart)])->all();
        return $this->render('/shoppingcart',[
            'quantities' => $this->cart,
            'products' => $products,
            'totalprice' => 0]
        );
    }
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->cart = \Yii::$app->session->get('cart',[]);
    }
    public function afterAction($action, $result)
    {
        \Yii::$app->session->set('cart',$this->cart);
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    public function actionAdd($productId, $quantity = 1) {
        // добалвение в корзину
        if(isset($this->cart[$productId]))
        {
            $this->cart[$productId] += $quantity;
        }
        else
        {
            $this->cart[$productId]=$quantity;
        }
        return $this->goBack();
    }
    public function actionDelete($productId) {
        if(isset($this->cart[$productId]))
        {
            unset($this->cart[$productId]);
        }
        return $this->redirect(['index']);
    }
}